[package]
name = "ai-training-week-1-section-2"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
term_size = "0.3.2"
